### ISSUE TITLE
Discuss: How to handle templates inside agent configs

### ISSUE THREAD

**Issue by ruflin** [elastic/package-registry#279]
Some of the Filebeat configs today contain template variables which are resolved during runtime. An example is the [mysql error log fileset]. It has the following lines inside: 

```
var:
  - name: paths
    default:
      - /var/log/mysql/error.log*
      - /var/log/mysqld.log*
    os.darwin:
      - /usr/local/var/mysql/{{.builtin.hostname}}.{{.builtin.domain}}.err*
    os.windows:
      - "c:/programdata/MySQL/MySQL Server*/error.log*"
```

`.builtin.hostname` and `.builtin.domain` are resolved by filebeat and filled in as soon as the module is started.

With Agent and Fleet, we have two places where these variables could be replaced. If this happens in Fleet, Fleet would take the metadata sent up by the agent and replace is inside the config. Then it delivers the config to the Agent. It means the config for each agent needs special processing.

The alternative is doing it on the agent side. Before a config file is loaded, it is run through a template engine and known variables are replaced. 

In any case, the template language used should be standardised (we use handlebars in a few places already) and the fields which can be used must be documented. It should be as few as possible.

**Comment by ruflin** [comment]
@jen-huang @ph @nchaulet Would be great to get your view on the above.

**Comment by jen-huang** [comment]
I favor doing it on the agent side as this will offer more flexibility for users who are using agents without Fleet. They can still build the config in the UI, keeping the templated vars, and deploy on multiple agents without having to adjust the config for each agent.

Btw, the vars structure should be like this, right? (`default` duplicated under each platform):
```
    os.darwin:
      default:
        - /usr/local/var/mysql/{{.builtin.hostname}}.{{.builtin.domain}}.err*
    os.windows:
      default:
        - "c:/programdata/MySQL/MySQL Server*/error.log*"
```
