### ISSUE TITLE
Add "data" asset type

### ISSUE THREAD

**Issue by ruflin** [elastic/package-registry#531]
Add support to the package to add data. 

It needs to be defined which format this data is stored in the package.

**Comment by mtojek** [comment]
The description is too vague. Could you please add more details and a use case for such assets?

**Comment by ruflin** [comment]
We currently have 3 proposed use cases: 

* Install data for look ups
* Geo data for maps
* Example data

The issue will be filled with more details as soon as we pick it up. At the moment it's more a placeholder.

**Comment by P1llus** [comment]
Adding the details and the requirements at least from my personal perspective when it comes to allowing modules to include enrichment policies and the data to be used for the enrichment indices.

First let's describe exactly what the use case is and why it can make a big impact:

**Current behaviour:**
Each module and its related dataset(s) include at least 1 pipeline. This pipeline is used to parse, map and normalise the ingested events.
After normalisation is done, we usually set all our ECS fields based on certain logic.` If field X = Y then event.action = Z` as an example.

This creates certain issues and restrictions with how much we can actually enrich incoming events. This is because if the logic is simple, we would include a simple "if" condition to a pipeline and if its complex we would use a script processor. These requires script compilations quite often, the scripts to be cached and has a fair impact on performance in smaller scenarios and larger impact in bigger implementations.

Example condition:
```
  - set:
      if: "ctx._temp_.cisco.message_id == '338301'"
      field: "client.port"
      value: "{{destination.port}}"
```
Example Script(Line 503 to 926 could be removed):
https://github.com/elastic/beats/blob/bcce25750afc2f205abd8cfbaf810fe8389e2c62/x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml#L503


Now if I was a regular user, that parses, map and normalise the events myself, using an enrichment index makes much more sense, it removes all logic needed and drills it down to just(just an example):
```
PUT /_enrich/policy/users-policy
{
    "match": {
        "indices": "cisco-module",
        "match_field": "id",
        "enrich_fields": ["ecs.type", "event.category", "event.type"]
    }
}
```

**Impact with enrichment index support in modules:**
If we decide for allowing a module itself to include a dataset involving the keys and values we want to use for enrichment, we would be able to remove a very large amount of logic from all modules that currently requires it, but also has many other benefits:

- All modules across all beats that would benefits from it would use the same method to manage ECS mapping the exact same way, making it much less straining to keep them updated for engineers.
- Customers sometimes modify pipelines them self, this would allow us to do a fair amount of our updates, especially on ECS to never need to touch the pipeline.
- It could allow in the future to update ECS mappings as telemetry and not just from package updates.
- Script compilations significantly reduced.
- Ability for customers to reuse the methodology, allowing them to add custom mappings if needed.
- Running a large amount of different modules/filesets will cause much less strain on the stack.
- Ability to either unify enrichment between modules by reusing the same mapping or make them module specific.

**How would an implementation look like?**
In addition to the current filebeat (as an example) directory structure, it should also include a folder for enrichment. This folder could include multiple datasets, a config file that references which index to be created for each dataset, and a config file for the enrichment policies to be applied.

**Installation**
When a package is installed through ingest management, the same process as now will be followed, but with 3 added steps:
Iterate over datasets and create temp indices for this dataset.
Create the enrichment policies defined by the module.
Executes the policy and then deletes the temp indices as they are not needed anymore.

**Package update**
When a package is updated, the enrichment index, policy and datasets should be deleted and remade.

**Package deletion**
All related enrichment policies and indices should be removed as well.


Hopefully this makes sense, and looking forward to hear any thoughts!

**Comment by leehinman** [comment]
# Use case
In AWS cloudtrail we have the situation where one of the log fields
allows us to set 3 of the ECS categorization fields.  For example:

a cloudtrail eventName (which gets mapped to event.action) of
"AddUserToGroup" would tell us to set event.kind to "event",
event.category to "[iam]", and event.type to "[change, group]"

This pattern has resulted in the following script processor in the
ingest pipeline, which happens to look an awful lot like an
enrichment

``` yaml
  - script:
      lang: painless
      ignore_failure: true
      params:
        AddUserToGroup:
          category:
            - iam
          kind: event
          type:
            - group
            - change
        .
        .
        .
        UpdateUser:
          category:
            - iam
          kind: event
          type:
            - user
            - change			
      source: >-
        def hm = new HashMap(params.get(ctx.event.action));
        hm.forEach((k, v) -> ctx.event[k] = v);
```

AWS cloudtrail has thousands of eventNames, it would be nice to replace
this script processor with an enrichment processor.  This would help
separate the data from the code and make it easier for users to update
the mappings in the field.

pipeline
``` yaml
- enrich:
    policy_name: cloudtrail-eventname-policy
    field: event.action
    target_field: event
    max_matches: 1
```

policy
``` yaml
- match:
    indices: cloudtrail-eventname
    match_field: action,
    enrich_fields:
      - category
      - kind
      - type
```

doc
``` yaml
action: UpdateUser
category:
  - iam
kind: event
type:
  - user
  - change			
```
