### ISSUE TITLE
Rethink how os specific configs should look like

### ISSUE THREAD

**Issue by ruflin** [elastic/package-registry#548]
Some configs are OS specific, like log paths. We initially had the following format in packages:

```
streams:
  - input: logs
    title: Title of the stream
    description: Description of the stream with more details.
    template_path: logs.yml
    vars:
      - name: paths
        required: true
        description: Paths to the nginx error log file.
        type: text
        multi: true
        default:
          - /var/log/nginx/error.log*
        # I suggest to use ECS fields for this config options here: https://github.com/elastic/ecs/blob/master/schemas/os.yml
        # This would need to be based on a predefined definition on what can be filtered on
        os.darwin:
          default:
            - /usr/local/var/log/nginx/error.log*
        os.windows:
          default:
            - c:/programdata/nginx/logs/*error.log*
```

We removed it again to keep the door open to rethink it when we actually start using it. This issue is to come up with a new / same proposal.
