### ISSUE TITLE
GET /package/${pkgName}/${pkgVersion} does not return policy_template.vars for input packages

### ISSUE THREAD

**Issue by hop-dev** [elastic/package-registry#864]
I am using the custom_logs-1.0.0 example input package to develop the Fleet side of input packages work: https://github.com/elastic/kibana/issues/137750

When retrieving the package from the 8.3.3 package registry (also tried main) the `GET /package/${pkgName}/${pkgVersion}` endpoint, policy_template.vars is not returned, here is a relevant snippet from the manifest.yml:

```yaml
format_version: 1.0.0
name: custom_logs
title: Custom Logs
description: >-
  Read lines from active log files with Elastic Agent.
type: input
version: 1.2.0-beta
license: basic
categories:
  - custom
policy_templates:
  - name: first_policy_template
    type: logs
    title: Custom log file
    description: Collect your custom log files.
    input: logfile
    template_path: input.yml.hbs
# vvvvvvvvvv THIS IS NOT RETURNED vvvv
    vars:
      - name: paths
        type: text
        title: Paths
        multi: true
        required: true
        show_user: true
      - name: tags
        type: text
        title: Tags
        multi: true
        required: true
        show_user: false
      - name: data_stream.dataset
        type: constant_keyword
        description: Data stream dataset.
        required: true
        show_user: true
      - name: ignore_older
        type: text
        title: Ignore events older than
        required: false
        default: 72h
```

Here is the policy_templates in the API response:

```
"policy_templates": [
            {
                "name": "first_policy_template",
                "title": "Custom log file",
                "description": "Collect your custom log files.",
                "multiple": true,
                "type": "logs",
                "input": "logfile",
                "template_path": "input.yml.hbs"
            }
        ],
```
